apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}